// Flag mappings from FlagCDN
export const TEAM_FLAGS = {
  'Algeria': 'dz',
  'Argentina': 'ar',
  'Australia': 'au',
  'Austria': 'at',
  'Belgium': 'be',
  'Bosnia and Herzegovina': 'ba',
  'Brazil': 'br',
  'Cabo Verde': 'cv',
  'Canada': 'ca',
  'Colombia': 'co',
  'Congo DR': 'cd',
  "Cote d'Ivoire": 'ci',
  'Croatia': 'hr',
  'Curacao': 'cw',
  'Czechia': 'cz',
  'Ecuador': 'ec',
  'Egypt': 'eg',
  'England': 'gb-eng',
  'France': 'fr',
  'Germany': 'de',
  'Ghana': 'gh',
  'Haiti': 'ht',
  'IR Iran': 'ir',
  'Iraq': 'iq',
  'Japan': 'jp',
  'Jordan': 'jo',
  'Korea Republic': 'kr',
  'Mexico': 'mx',
  'Morocco': 'ma',
  'Netherlands': 'nl',
  'New Zealand': 'nz',
  'Norway': 'no',
  'Panama': 'pa',
  'Paraguay': 'py',
  'Portugal': 'pt',
  'Qatar': 'qa',
  'Saudi Arabia': 'sa',
  'Scotland': 'gb-sct',
  'Senegal': 'sn',
  'South Africa': 'za',
  'Spain': 'es',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Tunisia': 'tn',
  'Turkiye': 'tr',
  'United States': 'us',
  'Uruguay': 'uy',
  'Uzbekistan': 'uz'
};

export const STAGE_LABELS = {
  'group-stage': 'Fase de Grupos',
  'round-of-32': 'Dieciseisavos de Final',
  'round-of-16': 'Octavos de Final',
  'quarter-finals': 'Cuartos de Final',
  'semi-finals': 'Semifinales',
  'third-place': 'Tercer Puesto',
  'final': 'Final'
};
